### PR TITLE
Typos / spelling fixes in msprime.c

### PR DESCRIPTION
**Pull request by ashander**
A pedantic contribution ;-)

### CODE REVIEW

**Comment by ashander** [comment]
:disappointed: pedantic on typos, careless on code.  I'll fix this

**Comment by jeromekelleher** [comment]
Thanks a lot @ashander, I didn't realise there were so many typos!

Re #197,  is there an "All checks have failed" section at the bottom? I'm wondering if GitHub doesn't show these status boxes to other users.

**Comment by ashander** [comment]
Ha. I didn't either. I started out fixing one and thought it was annoying
to make such a small PR so should run spell check on the rest of the
comments.

Sorry if #197 was unclear: I **do** see the "all checks failed" section on
the PR.

What's confusing:

- I get GH notifications for a comment from codecov that says, basically,
"looks good!"
- I get no notifications for the failing checks. I have to go back to look
at the PR to realize it failed.

It's not a big deal but a little strange. Maybe some configuration on
codecov side can prevent them from commenting if CI fails?

**Comment by ashander** [comment]
So, for example yesterday I fixed the missing `}` that caused the failures on my local branch but I ran
```
git commit --amend --no-edit
git push -f origin patch-2
```
and logged out before realizing that no change was pushed. I didn't realize the checks were still failing till I saw your comment. I've just done
```
git commit --amend --no-edit -a
git push -f origin patch-2
```
so hopefully these will work.

**Comment by jeromekelleher** [comment]
> It's not a big deal but a little strange. Maybe some configuration on codecov side can prevent them from commenting if CI fails?

Ah, gotcha,  good point. This should be possible, I'll take a look.

**Comment by jeromekelleher** [comment]
All looking good, thanks again @ashander.

**Pull request merged**
