### PR TITLE
compute SFS

### PR DESCRIPTION
**Pull request by petrelharp**
I knocked together SFS calculations by modifying tree_stat_vector.  Everything seems to check out, agreeing with naive python versions, but I'm a bit nervous that I'm not testing things properly.  I think we should merge it, though, if nothing turns up.

@hyanwong - see if this does what you want?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good to me. There's a lot of duplicated code here which we should try to refactor at some point; it seems the basic structure of a lot of these algorithms is the same, with only the internal stats updates changing a bit. No hurry for now, but something to think about.

Looks like some real test failures in the CI, so probably a logic bug somewhere though.

**Comment by petrelharp** [comment]
Refactoring: yes, definately!  But, not quite yet.

**Comment by petrelharp** [comment]
Hm, ok - looks like the only problem *may* have been in the 0th entry of the SFS, which was meaningless anyhow.  I've removed that entry, and added more ts to the checks.

I'm leaving the `n`th entry in, though...

**Comment by petrelharp** [comment]
how's that?  @hyanwong, want to take a look?

**Comment by petrelharp** [comment]
i think we can merge this.

**Comment by jeromekelleher** [comment]
Merging.

**Pull request merged**
