### PR TITLE
Test xi dirac

### PR DESCRIPTION
**Pull request by shajoezhu**
see https://github.com/shajoezhu/msprime/issues/22

Verificaion:
```
python3 verification.py xiDirac_kingman
```

mutation_d
mutation_h
mutation_pi
mutation_ss
mutation_thetah

### CODE REVIEW

**Comment by shajoezhu** [comment]
coalescent time scaling is not right ...

coalescent_ca_events
coalescent_mig_events_0
coalescent_num_trees
coalescent_re_events
coalescent_t

**Comment by jeromekelleher** [comment]
Perfect, thanks @shajoezhu! This time scaling is tricky, let's have a chat about it and see if we can pinpoint the problem.

**Comment by shajoezhu** [comment]
Think now is working

coalescent_ca_events
coalescent_mig_events_0
coalescent_num_trees
coalescent_re_events
coalescent_t
mutation_d
mutation_h
mutation_pi
mutation_ss
mutation_thetah

**Comment by jeromekelleher** [comment]
Beautiful! Thanks @shajoezhu, great work. Merging.

**Pull request merged**
