### PR TITLE
Add tree traversals to tree.py

### PR DESCRIPTION
**Pull request by td329**
Added 'inorder', 'postorder' and 'levelorder' (='breadthfirst') tree traversals to tree.py.

Not sure if these are the most efficient or cleanest approaches but they should work. Example output:

{0: 12, 1: 14, 2: 11, 3: 15, 4: 13, 5: 12, 6: 11, 7: 13, 8: 10, 9: 10, 10: 14, 11: 15, 12: 16, 13: 18, 14: 16, 15: 17, 16: 17, 17: 18, 18: -1} 

preorder: [18, 13, 4, 7, 17, 15, 3, 11, 2, 6, 16, 12, 0, 5, 14, 1, 10, 8, 9]
postorder: [4, 7, 13, 3, 2, 6, 11, 15, 0, 5, 12, 1, 8, 9, 10, 14, 16, 17, 18]
inorder: [4, 13, 7, 18, 3, 15, 2, 11, 6, 17, 0, 12, 5, 16, 1, 14, 8, 10, 9]
levelorder: [18, 13, 17, 4, 7, 15, 16, 3, 11, 12, 14, 2, 6, 0, 5, 1, 10, 8, 9]

image

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks @td329, these are beautiful! A great addition to the API. We just need some tests, and I think we can merge this pretty quickly.

I guess what we need here are some test cases to make sure that the orders behave like we want them to. To do this:

1. Add simple recursive versions of these orderings to the ``PythonSparseTree`` class in ``tests/__init__.py``.
2. Add tests for these orders in ``tests/test_highlevel.py:TestSparseTree.test_traversals``.

**Comment by jeromekelleher** [comment]
Also, there are some PEP8 violations causing CI to fail. If you run ``flake8 --max-line-length 89 msprime tests`` this will pick these out for you.

Thanks again!

**Comment by td329** [comment]
Thanks for the pointers, @jeromekelleher. I've added some tests. The level-order test is a little contrived, but I think gets at what we need it to do. The others are standard recursive algorithms for depth-first search. 

Unit testing seems to check out when I run locally. Trying to figure out why CI is failing. flake8 passes when I run this side.

**Comment by jeromekelleher** [comment]
Looks great to me @td329! I hadn't seen the "levelorder" algorithm before so was slightly sceptical about whether this is useful, but if it's something that you need then I'm very happy to include it.

Would you mind rebasing your branch off upstream/master and squashing down the commits a bit please? If you don't know how to do this, you need to:

1. Set up a remote for the upstream repo: https://help.github.com/articles/configuring-a-remote-for-a-fork/
2. Run git rebase -i upstream master, and put an 's' in front of the commits you want to squash. 
3. Force push your rebased branch.

We just want to get rid of the 'fixing typo' commits from the history, which don't really help later when we're trying to do things like git bisect and stuff.

Thanks again for the PR, it's a very nice addition to the API!

**Comment by td329** [comment]
Sorry! I'm unfamiliar with the git pipeline. Think I've stuffed this up. Trying to fix now.

**Comment by jeromekelleher** [comment]
No worries; sorry to put you through this. Feel free to drop me an email if it's all getting too messy. The good news is that everything is fixable in git --- you just need to know the right magic sequence of commands. Rebasing/squashing is generally quite handy, so it's worth the effort!

**Comment by jeromekelleher** [comment]
I had a quick look at your fork, and I think you're OK. Your master is in the correct state I think. So, just do something like

```
git pull
git checkout master
git checkout -b new_tree_traversals
git push origin new_tree_traversals
```
and create a new PR from that branch.

**Pull request closed without merging**
