### PR TITLE
Add 'alleles' list to Variant object.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Issue #301

This should be the last structural change before 0.5.0, and put us in a position to finalise everything to do with sites and mutations.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This is getting ready to merge, and is real progress towards handling general mutational patterns effectively. To recap, the basic idea is that we now have an ``alleles`` tuple that is attached to the variant object returned by ``variants``. The values in the ``genotypes`` arrays are then indexes into this array. So, if we have a site with observations (indexed by sample order) ["AA", "C", "T", "G"] and the ancestral state was "G", then we'd have 
```python
variant.alleles == ("G", "AA", "C", "T")
variant.genotypes == [1, 2, 3, 0]
```
The ordering of the alleles is decided by the ordering of the underlying mutations. The ancestral state will always be the zeroth allele. This seems quite nice because we can now support any arbitrary pattern of mutations at a given site, but without breaking anyone's existing code that assumes binary mutations.

I've also updated the ``variants()`` iterator to return a new object every time for the genotypes array (see #253). 

Another tweak I made was to remove the mutation generator from the WF simulator. This was causing problems because the mutations were not consistent (i.e., we could have A->A transitions), and it seemed like a lot of work to make them so. It seemed a lot simpler to just follow our own advice and use the Jukes-Cantor generator on the resulting tree sequence.

I need to do a few more tests just to be completely that it all works for some corner cases, but I think it's ready to merge after that.

@petrelharp, do you have any thoughts here?

**Comment by jeromekelleher** [comment]
For the record, this should close 
- #253
- #301 
- #169

**Comment by petrelharp** [comment]
This sounds good, but I'd like to be clear about the problems with the WF mutation generator.  Where do  problems occur if there are A->A transitions?

**Comment by jeromekelleher** [comment]
> This sounds good, but I'd like to be clear about the problems with the WF mutation generator. Where do problems occur if there are A->A transitions?

When generating haplotypes and variants, we check if the derived state has already been set for each sample it subtends, and raise an error if it does. See

https://github.com/jeromekelleher/msprime/blob/variant-alleles/lib/vargen.c#L154

It's debatable whether this is a good idea, but the original thinking (ie., specifying an A->A transition) would be the result of a mistake, and so it's a useful error checking feature. The reason this wasn't an issue before is because the haplotype generator mistakenly wasn't checking for this, in this general string case.

I'd imagine that we can add a flag to the variant and haplotype generators to turn off this error checking if we do want to allow these mutations.

**Comment by jeromekelleher** [comment]
Ah, looking at this code again and I realise that we are assuming a (weak) tree pre-ordering for the mutations. So, the question is, do we continue to rely on this ordering, or rejigger things a bit to use the mutation.parent field?

**Comment by petrelharp** [comment]
re: A->A transitions - I fall on the side of allowing mutations that don't change anything, if this doesn't actually break anything, but could go either way.

Which code is assuming the tree ordering?

**Comment by petrelharp** [comment]
About assuming ordering in `vargen_update_site` - I agree, it is correct.  Should perhaps insert a comment saying that we use this fact here.

**Comment by jeromekelleher** [comment]
OK, merging this. I've moved discussion of the degenerate mutations issue over to #329.

**Pull request merged**
