### PR TITLE
test with WF simulator

### PR DESCRIPTION
**Pull request by petrelharp**
There is currently a bug (#230) - as far as I can tell, in the simplify machinery, although maybe I'm being dense.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good, thanks @petrelharp.

Given that the simulator is so simple, I think it's probably best to just put all this into one file --- say, ``tests/test_wright_fisher.py``? Otherwise there's a lot of chasing references around to try and find out where the code actually is. (This contradicts what I said before, I know, but I had imagined it would need a lot more code and be more complicated.)

**Comment by petrelharp** [comment]
I've rebased this to master and moved the machinery.

This will have ancestral samples, thanks to overlapping generations.  I've bumped up the survival probability for some of the tests to 0.9 to ensure this happens a lot.

**Comment by jeromekelleher** [comment]
Great, thanks @petrelharp. As you're off for a while, shall I take it from here and see if I can get to the bottom of these ancestral samples bugs?

**Comment by petrelharp** [comment]
That'd be wonderful.  Also note the `simplify_tables` test that fails for mysterious (to me) reasons.

**Comment by jeromekelleher** [comment]
A note on progress here. The tests are passing here after a tweak to the simplify algorithm, but I'm not happy that it's fully correct, as we're leaking segments (which is nearly always a sign of a bug in these algorithms). Unless overlapping generations is on the critical path for anyone, I'd like to spend a bit more time and try to fully iron out the details here. If someone needs this code ASAP we can merge now and work on the algorithm in another PR.

**Comment by jeromekelleher** [comment]
Progress here. While I'm still not happy with the underlying algorithm here, I can't find any cases where I can break it. Therefore, in the interest of moving on and making progress I think we should merge this much and try it out with various inputs. Hopefully the assertions will catch things if anything weird happens.

What do you think @petrelharp? Basically I've tweaked the simplify algorithm a bit, and done more testing with your WF framework. I've disabled mutation generation, as I didn't have time to go through it properly and write tests for it. I think we could add this as a TODO issue (write tests for WF simplify with mutations). As for the algorithm, hopefully it's correct now and it's just not handling ancestral samples very elegantly. I'm sure this inelegance will become clear when we start writing it up and hopefully a solution will be found.

**Comment by jeromekelleher** [comment]
Merging this as it's a substantial improvement over what's currently in master.

**Pull request merged**
