### PR TITLE
Changed to 'square' tree layout.

### PR DESCRIPTION
**Pull request by jeromekelleher**
This is a work in progress to improve tree drawing in msprime.

What do people think of "square" trees versus "triangular" trees? The consensus seems to be for square trees, so I think msprime's tree drawing should go along with this. Pinging @petrelharp and @ashander for opinions! 

Here's an example from the new code:

tree_0

@koelling, this fixes issue #206.

TODO:
1. Provide an option to rescale the branch lengths so it's easier to see the topology
2. Fix non binary tree handling
3. Return SVG as described in #204 
4. More?

### CODE REVIEW

**Comment by petrelharp** [comment]
I love it!

**Comment by petrelharp** [comment]
I'm trying to resist the temptation to write something that will print them in ascii.

Oh, but it already exists: http://etetoolkit.org/

**Comment by jeromekelleher** [comment]
> Oh, but it already exists: http://etetoolkit.org/

It's true, it does feel like a waste of effort making yet another tree viz method. I'm not all that keen on having a dependency on ete or dendropy or anything though, and I'm not sure how you would go about annotating their trees with mutations. Also, I'm hoping to write some real *tree sequence* visualisations some day, which will definitely need to be bespoke.

So, I'd be happy if you lost your fight against temptation @petrelharp!

**Comment by petrelharp** [comment]
sounds good to me.  those ones you've got are great.

**Comment by ashander** [comment]
Square looks good, and seems easier to sprinkle with mutations. Great stuff!

**Comment by ashander** [comment]
Re @petrelharp comments: it would be great to have something that could be used either with `__str__` (or `__repr__` for even less typing) to printed an ascii tree in the REPL. but this is of limited utility (mostly for debugging and interaction with small tree examples).

**Pull request merged**
