### PR TITLE
Sphinx/IPython integration into docs

### PR DESCRIPTION
**Pull request by molpopgen**
Here are some initial commits for #240.  

I tested that "make html" worked on my machine, but have not tested that all the RTD environment stuff works.

The bigger issue is that the msprime objects are mocked, so that "print(n)" in the example displays something like 

```
<MagicMock id='4536862424'>
``` 
instead of the contents of a NodeTable object.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks for this @molpopgen. I hadn't thought about the consequences of running code on RTD though, which is a fundamental problem. I think that unless they allow users to install package from conda it's going to be very difficult to get this to work. The GSL and HDF5 library dependencies are a major pain for stuff like this, and is the reason that I mocked out all the low level module stuff.

How do you deal with compiling stuff on RTD and library dependencies?

**Comment by molpopgen** [comment]
> How do you deal with compiling stuff on RTD and library dependencies?

I have the yml files set up to use conda to pull in dependencies.  I've done this for two projects now.  It is fickle!  There are some other tweaks re: actually building a Python extension in C/C++ that are specific to RTD (and quite poorly documented there, IMO).  I'll try to point out what to do, but I'll need to look at my own conf.py files first....

**Comment by molpopgen** [comment]
> How do you deal with compiling stuff on RTD and library dependencies?

Here is fwdpy11's environment.yml, which goes in docs/: https://github.com/molpopgen/fwdpy11/blob/master/doc/environment.yml

It specifies the dependencies.  Pip means pip, and all else gets pulled in via conda.

On RTD itself, you have to click a few options in the settings to enable conda.

There are some nuances to paths in the conf.py related to building on RTD.  Some of them you'll see in the fwdpy11 conf.py: https://github.com/molpopgen/fwdpy11/blob/master/doc/conf.py  

Look for READTHEDOCS in the conf.py, which is an environment variable set on that system.

**Comment by jeromekelleher** [comment]
OK cool! If you let me know when you're happy with this branch, I'll see if I can get the conda stuff working on RTD.

**Comment by jeromekelleher** [comment]
As noted over in #240, unfortunately I don't think it's straightforward to get msprime building on RTD. Sorry to waste your time on this @molpopgen; we'll get this integrated at some point, but there are rather bigger fish to fry right now.

**Comment by molpopgen** [comment]
> As noted over in #240, unfortunately I don't think it's straightforward to get msprime building on RTD. Sorry to waste your time on this @molpopgen; we'll get this integrated at some point, but there are rather bigger fish to fry right now.

@jeromekelleher No problem.  We can revisit this later.  It is definitely more important to get the other various issues sorted out first.  I had to look up what sphinx/argparse does, and I learned that I'm likely to confront this issue, as I want to add console scripts to [pylibseq](http://github.com/molpopgen/pylibseq) and possibly to [fwdpy11](http://github.com/molpopgen/fwdpy11)

**Comment by jeromekelleher** [comment]
Cool, thanks @molpopgen. I'm going to close this PR for now so, we can dig it up again in the future when we need it.

**Pull request closed without merging**
